---
title: Columbia británica
tagline: el mejor lugar del mundo
disqus:
  comments: false
  disqus_shortname: 
menu:
- {name: 'Acerca', path: 'menu', url: 'acerca.html'}
- {name: 'Textos', path: 'menu', url: 'textos.html'}
pagination:
  next_page: Newer
  previous_page: Older
post_date_prefix: Escrito en
